# Generated by Django 5.0 on 2025-08-31 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('probability', models.FloatField(help_text='Probability percentage (all segments should sum to ~100)')),
                ('type', models.CharField(choices=[('try_again', 'Try Again'), ('coupon', 'Coupon'), ('quebes', 'Quebes'), ('gift_card', 'Gift Card')], max_length=20)),
                ('link_section', models.CharField(blank=True, max_length=200, null=True)),
                ('link_category', models.CharField(blank=True, max_length=200, null=True)),
                ('link_offer', models.CharField(blank=True, max_length=200, null=True)),
                ('reward_value', models.CharField(blank=True, help_text='Quebes count / Coupon code / Gift info', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpinSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.PositiveIntegerField(default=1, help_text='Max spins allowed per user per day')),
            ],
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spinwheel.spinsegment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
