# Generated by Django 5.0 on 2025-08-29 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkRewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Day number in challenge (1..30 etc.)')),
                ('min_steps', models.IntegerField()),
                ('max_steps', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('reward_type', models.CharField(choices=[('coupon', 'Coupon'), ('gift_card', 'Gift Card'), ('quebes', 'Quebes'), ('discount', 'Discount'), ('trial_product', 'Trial Product'), ('other', 'Other')], max_length=50)),
                ('reward_section', models.CharField(blank=True, max_length=200, null=True)),
                ('reward_category', models.CharField(blank=True, max_length=200, null=True)),
                ('reward_offer', models.CharField(blank=True, max_length=200, null=True)),
                ('reward_value', models.CharField(blank=True, help_text='Ex: 20% OFF, 5 Quebes, Free Trial Product', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('day',),
            },
        ),
        migrations.CreateModel(
            name='WalkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('reward_unlocked', models.BooleanField(default=False)),
                ('reward_value', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('user', 'day')},
            },
        ),
    ]
