# Generated by Django 5.0 on 2025-08-29 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Milestone Set',
                'verbose_name_plural': 'Milestone Sets',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('feedback_schema', models.JSONField(blank=True, null=True)),
                ('milestone_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='milestones.milestoneset')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('milestone_set', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='locked', max_length=20)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='milestones/screenshots/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('feedback_answers', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_milestones', to='milestones.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'milestone')},
            },
        ),
    ]
