# Generated by Django 5.0 on 2025-09-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
        ('performandearn', '0002_performtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestoneset',
            options={},
        ),
        migrations.AddField(
            model_name='milestoneset',
            name='perform_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perform_milestone_sets', to='performandearn.performandearn'),
        ),
    ]
