# Generated by Django 5.2.5 on 2025-09-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ques3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referral_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='smart_rank_score',
        ),
    ]
