# Generated by Django 5.0 on 2025-08-11 06:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandStore',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_offer_name', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('offer_brand_info', models.TextField(blank=True, null=True)),
                ('offer_brand_benefits', models.TextField(blank=True, null=True)),
                ('milestone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('milestone_type', models.CharField(blank=True, max_length=100, null=True)),
                ('milestone_description', models.TextField(blank=True, null=True)),
                ('milestone_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brandstore/logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='brandstore/banners/')),
                ('offer_video_file', models.FileField(blank=True, null=True, upload_to='brandstore/videos/')),
                ('offer_video_youtube', models.URLField(blank=True, null=True)),
                ('task_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referral_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offer_url', models.URLField(blank=True, null=True)),
                ('share_and_earn_enabled', models.BooleanField(default=False)),
                ('travel_required', models.BooleanField(default=False)),
                ('fraud_flag', models.BooleanField(default=False)),
                ('sponsored_flag', models.BooleanField(default=False)),
                ('smart_rank_score', models.IntegerField(default=0)),
                ('smart_rank_score_filter', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('conversion_window_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geo_targeting', models.CharField(blank=True, max_length=255, null=True)),
                ('user_targeting_tags', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
