# Generated by Django 5.0 on 2025-08-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandstore',
            old_name='share_and_earn_enabled',
            new_name='available_to_il1',
        ),
        migrations.RenameField(
            model_name='brandstore',
            old_name='store_id',
            new_name='brand_store_id',
        ),
        migrations.RenameField(
            model_name='brandstore',
            old_name='milestone_description',
            new_name='brand_store_milestone_description',
        ),
        migrations.RenameField(
            model_name='brandstore',
            old_name='offer_url',
            new_name='brand_store_offer_url',
        ),
        migrations.RenameField(
            model_name='brandstore',
            old_name='referral_payout',
            new_name='brand_store_referral_payout',
        ),
        migrations.RenameField(
            model_name='brandstore',
            old_name='task_payout',
            new_name='brand_store_task_payout',
        ),
        migrations.RenameField(
            model_name='brandstore',
            old_name='smart_rank_score',
            new_name='offer_position_rank',
        ),
        migrations.RemoveField(
            model_name='brandstore',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='brandstore',
            name='smart_rank_score_filter',
        ),
        migrations.RemoveField(
            model_name='brandstore',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='brandstore',
            name='android_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='brand_store_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='brand_store_offer_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='brand_store_payout_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='brand_store_sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='brand_store_terms_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='carousel_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='brand_store/carousel/'),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='carousel_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='brand_store/carousel/'),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='carousel_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='brand_store/carousel/'),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='carousel_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='brand_store/carousel/'),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='click_behavior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='credit_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='custom_cta_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='daily_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='featured_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='imei_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='link_to_contest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='minimum_cart_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='my_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='offer_wall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='platform_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='review_module_for_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='show_in_sections',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='success_ratio_req',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='task_of_the_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='tracking_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='trigger_badge_unlock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandstore',
            name='whom_to_sell_how_it_works',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandstore',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_store/banners/'),
        ),
        migrations.AlterField(
            model_name='brandstore',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_store/logos/'),
        ),
        migrations.AlterField(
            model_name='brandstore',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='brandstore',
            name='geo_targeting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandstore',
            name='offer_video_file',
            field=models.FileField(blank=True, null=True, upload_to='brand_store/videos/'),
        ),
        migrations.AlterField(
            model_name='brandstore',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='brandstore',
            name='user_targeting_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
