# Generated by Django 5.2.5 on 2025-09-03 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandstore', '0002_rename_share_and_earn_enabled_brandstore_available_to_il1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandstore',
            name='brand_store_milestone_description',
        ),
        migrations.RemoveField(
            model_name='brandstore',
            name='milestone_name',
        ),
        migrations.RemoveField(
            model_name='brandstore',
            name='milestone_payout',
        ),
        migrations.RemoveField(
            model_name='brandstore',
            name='milestone_type',
        ),
        migrations.CreateModel(
            name='BrandStoreMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=255)),
                ('milestone_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('brand_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='brandstore.brandstore')),
            ],
        ),
    ]
