# Generated by Django 5.0 on 2025-08-31 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_section', models.CharField(blank=True, max_length=200, null=True)),
                ('trigger_category', models.CharField(blank=True, max_length=200, null=True)),
                ('trigger_offer', models.CharField(blank=True, max_length=200, null=True)),
                ('reward_type', models.CharField(choices=[('discount', 'Discount'), ('quebes', 'Quebes'), ('product', 'Trial Product'), ('coupon', 'Coupon'), ('gift_card', 'Gift Card'), ('other', 'Other')], max_length=50)),
                ('reward_section', models.CharField(blank=True, max_length=200, null=True)),
                ('reward_category', models.CharField(blank=True, max_length=200, null=True)),
                ('reward_offer', models.CharField(blank=True, max_length=200, null=True)),
                ('reward_value', models.CharField(blank=True, help_text='Ex: 20% OFF, 5 Quebes, Free Trial Product, Coupon Code', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScratchCardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_scratched', models.BooleanField(default=False)),
                ('reward_revealed', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scratchcards.scratchcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
