# Generated by Django 5.0 on 2025-08-31 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('milestones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformAndEarn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('offer_brand_info', models.TextField()),
                ('offer_brand_benefits', models.TextField(blank=True, null=True)),
                ('terms_conditions', models.TextField()),
                ('how_to_earn', models.TextField(blank=True, null=True)),
                ('whom_to_sell', models.TextField(blank=True, null=True)),
                ('offer_logo', models.ImageField(upload_to='performandearn/logo/')),
                ('offer_banner', models.ImageField(upload_to='performandearn/banner/')),
                ('offer_video_file', models.FileField(blank=True, null=True, upload_to='performandearn/videos/')),
                ('offer_video_url', models.URLField(blank=True, null=True)),
                ('task_payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referral_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pe_offer_link', models.URLField()),
                ('share_and_earn_enabled', models.BooleanField(default=False)),
                ('travel_required', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('daily_task', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('credit_type', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_type', models.CharField(default='Postback', max_length=50)),
                ('payout_time_info', models.CharField(max_length=255)),
                ('task_of_day', models.BooleanField(default=False)),
                ('confirmation_time', models.CharField(default='24h', max_length=100)),
                ('available_for_level1', models.BooleanField(default=True)),
                ('featured_partner', models.BooleanField(default=False)),
                ('pe_custom_cta_label', models.CharField(blank=True, max_length=100, null=True)),
                ('pe_no_people_availed', models.CharField(blank=True, max_length=100, null=True)),
                ('pe_smart_rank_score_filter', models.BooleanField(default=False)),
                ('pe_smart_rank_score', models.IntegerField(default=0)),
                ('show_in_sections', models.CharField(default='general', max_length=100)),
                ('link_to_contest', models.BooleanField(default=False)),
                ('vendor_visibility', models.BooleanField(default=True)),
                ('platform_type', models.CharField(default='all', max_length=100)),
                ('pe_task_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('task_position_rank', models.IntegerField(default=0)),
                ('sponsored_flag', models.BooleanField(default=False)),
                ('fraud_flag', models.BooleanField(default=False)),
                ('success_ratio_required', models.BooleanField(default=False)),
                ('geo_targeting', models.TextField(blank=True, null=True)),
                ('user_targeting_tags', models.TextField(blank=True, null=True)),
                ('click_behavior', models.CharField(default='redirect', max_length=50)),
                ('offer_wall', models.BooleanField(default=False)),
                ('trigger_badge_unlock', models.BooleanField(default=False)),
                ('review_required', models.BooleanField(default=False)),
                ('website_task_review_module', models.TextField(blank=True, null=True)),
                ('my_lead', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='milestones.milestoneset')),
            ],
        ),
        migrations.CreateModel(
            name='UserPerformTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reward_credited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='performandearn.performandearn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perform_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
