# Generated by Django 5.0 on 2025-08-31 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
        ('performandearn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('pe_offer_link', models.URLField()),
                ('referral_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('callback_url', models.URLField(blank=True, help_text="Vendor's callback URL (if any)", null=True)),
                ('milestone_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perform_tasks', to='milestones.milestoneset')),
            ],
        ),
    ]
