# Generated by Django 5.0 on 2025-09-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_alter_milestoneset_options_milestoneset_perform_task'),
        ('performandearn', '0002_performtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performandearn',
            name='milestone_set',
        ),
        migrations.AddField(
            model_name='performandearn',
            name='milestone_sets',
            field=models.ManyToManyField(blank=True, related_name='perform_offers', to='milestones.milestoneset'),
        ),
        migrations.DeleteModel(
            name='PerformTask',
        ),
    ]
