# Generated by Django 5.0 on 2025-08-20 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_information', models.TextField(blank=True, null=True)),
                ('sku_description', models.TextField(blank=True, null=True)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='trialstore/logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='trialstore/banners/')),
                ('offer_video_file', models.FileField(blank=True, null=True, upload_to='trialstore/videos/')),
                ('offer_video_youtube', models.URLField(blank=True, null=True)),
                ('trial_store_referral_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('share_and_earn_enabled', models.BooleanField(default=False)),
                ('travel_required', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('daily_task', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('credit_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_type', models.CharField(blank=True, max_length=100, null=True)),
                ('trial_store_payout_info', models.TextField(blank=True, null=True)),
                ('task_of_the_day', models.BooleanField(default=False)),
                ('smart_rank_score_filter', models.BooleanField(default=False)),
                ('smart_rank_score', models.FloatField(default=0.0)),
                ('featured_offer', models.BooleanField(default=False)),
                ('custom_cta_label', models.CharField(blank=True, max_length=100, null=True)),
                ('show_in_sections', models.BooleanField(default=True)),
                ('link_to_contest', models.URLField(blank=True, null=True)),
                ('vendor_visibility', models.BooleanField(default=True)),
                ('platform_type', models.CharField(blank=True, max_length=50, null=True)),
                ('product_position_rank', models.IntegerField(default=0)),
                ('sponsored_flag', models.BooleanField(default=False)),
                ('fraud_flag', models.BooleanField(default=False)),
                ('success_ratio_req', models.FloatField(default=0.0)),
                ('geo_targeting', models.TextField(blank=True, null=True)),
                ('user_targeting_tags', models.TextField(blank=True, null=True)),
                ('click_behavior', models.TextField(blank=True, null=True)),
                ('offer_wall', models.BooleanField(default=False)),
                ('trigger_badge_unlock', models.BooleanField(default=False)),
                ('min_cart_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_inr_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_quebes_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('enable_max_user', models.BooleanField(default=False)),
                ('max_purchase_per_user', models.IntegerField(default=1)),
                ('inventory', models.IntegerField(default=0)),
                ('credited_at', models.DateTimeField(auto_now_add=True)),
                ('tiered_delivery', models.BooleanField(default=False)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_actual_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('how_to_use', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('key_benefits', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('trust_badge', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrialStoreAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=255)),
                ('ad_banner', models.ImageField(blank=True, null=True, upload_to='trialstore/ads/')),
                ('ad_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrialVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=20)),
                ('subscription_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrialProductCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trialstore/carousel/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='trialstore.trialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='TrialProductMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=255)),
                ('milestone_type', models.CharField(max_length=100)),
                ('milestone_description', models.TextField(blank=True, null=True)),
                ('milestone_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('feedback_required', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='trialstore.trialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='TrialStoreFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='trialstore.trialproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trialproduct',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_products', to='trialstore.trialvendor'),
        ),
    ]
