# Generated by Django 5.0 on 2025-08-20 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialstore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialAd',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('advertiser', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_type', models.CharField(choices=[('CPM', 'Cost Per Mille (1000 impressions)'), ('CPC', 'Cost Per Click')], default='CPM', max_length=10)),
                ('cpm_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cpc_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('frequency_cap', models.IntegerField(default=3, help_text='Max impressions per user for this ad')),
                ('boost_percentage', models.PositiveIntegerField(default=0, help_text='Increase cost by % (30,40,etc.)')),
                ('target_geo', models.CharField(blank=True, max_length=255, null=True)),
                ('target_tags', models.TextField(blank=True, help_text='Comma separated targeting tags', null=True)),
                ('platform_type', models.CharField(default='All', max_length=50)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='ads/banner/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='ads/video/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='trialstore.trialad')),
            ],
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='trialstore.trialad')),
            ],
        ),
    ]
