# Generated by Django 5.0 on 2025-08-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialstore', '0002_trialad_adimpression_adclick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adimpression',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='adimpression',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdClick',
        ),
        migrations.DeleteModel(
            name='TrialAd',
        ),
        migrations.DeleteModel(
            name='AdImpression',
        ),
    ]
