# Generated by Django 5.2.5 on 2025-09-07 05:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareAndEarnOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_id', models.CharField(max_length=50, unique=True)),
                ('offer_name_se', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('offer_brand_info_se', models.TextField()),
                ('offer_brand_benefits_se', models.TextField(blank=True, null=True)),
                ('offer_logo_se', models.ImageField(upload_to='shareandearn/logos/')),
                ('offer_banner_image_se', models.ImageField(upload_to='shareandearn/banners/')),
                ('se_offer_video_file', models.FileField(blank=True, null=True, upload_to='shareandearn/videos/')),
                ('se_offer_video_youtube', models.URLField(blank=True, null=True)),
                ('terms_conditions_se', models.TextField()),
                ('how_to_earn_se', models.TextField(blank=True, null=True)),
                ('whom_to_sell_se', models.TextField(blank=True, null=True)),
                ('task_payout_amount_se', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referral_payout_se', models.DecimalField(decimal_places=2, max_digits=10)),
                ('se_offer_link', models.URLField()),
                ('share_and_earn_enabled', models.BooleanField(default=True)),
                ('travel_required', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('daily_task', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('credit_type', models.CharField(max_length=50)),
                ('tracking_type', models.CharField(max_length=50)),
                ('payout_time_info', models.CharField(max_length=100)),
                ('task_of_the_day', models.BooleanField(default=False)),
                ('confirmation_time_hours', models.PositiveIntegerField(default=24)),
                ('available_for_level1', models.BooleanField(default=True)),
                ('featured_partner', models.BooleanField(default=False)),
                ('se_custom_cta_label', models.CharField(blank=True, max_length=100, null=True)),
                ('se_no_of_people_availed', models.PositiveIntegerField(default=0)),
                ('se_smart_rank_score_filter', models.CharField(blank=True, max_length=50, null=True)),
                ('se_smart_rank_score', models.FloatField(default=0.0)),
                ('show_in_sections', models.BooleanField(default=True)),
                ('link_to_contest', models.URLField(blank=True, null=True)),
                ('vendor_visibility', models.BooleanField(default=True)),
                ('platform_type', models.CharField(max_length=50)),
                ('se_task_tag', models.JSONField(default=list)),
                ('task_position_rank', models.PositiveIntegerField(default=0)),
                ('sponsored_flag', models.BooleanField(default=False)),
                ('fraud_flag', models.BooleanField(default=False)),
                ('success_ratio_req', models.FloatField(default=0.5)),
                ('click_behavior', models.CharField(default='default', max_length=50)),
                ('offer_wall', models.BooleanField(default=False)),
                ('trigger_badge_unlock', models.BooleanField(default=False)),
                ('review_for_task_required', models.BooleanField(default=False)),
                ('review_module_for_task', models.CharField(blank=True, max_length=255, null=True)),
                ('my_lead', models.BooleanField(default=False)),
                ('website_task_review_module_se', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ShareAndEarnMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=255)),
                ('milestone_type', models.CharField(max_length=50)),
                ('milestone_description', models.TextField()),
                ('milestone_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='shareandearn.shareandearnoffer')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_id', models.CharField(max_length=100)),
                ('referee_id', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='shareandearn.shareandearnoffer')),
            ],
            options={
                'unique_together': {('offer', 'referrer_id', 'referee_id', 'level')},
            },
        ),
    ]
