# Generated by Django 5.0 on 2025-08-14 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('brand_information', models.TextField(blank=True, null=True)),
                ('sku_description', models.TextField(blank=True, null=True)),
                ('milestone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('milestone_type', models.CharField(blank=True, max_length=100, null=True)),
                ('milestone_description', models.TextField(blank=True, null=True)),
                ('milestone_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('how_to_earn', models.TextField(blank=True, null=True)),
                ('whom_to_sell', models.TextField(blank=True, null=True)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='digitalstore/logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='digitalstore/banners/')),
                ('offer_video_file', models.FileField(blank=True, null=True, upload_to='digitalstore/videos/')),
                ('offer_video_youtube', models.URLField(blank=True, null=True)),
                ('referral_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('share_and_earn_enabled', models.BooleanField(default=False)),
                ('travel_required', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_task', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('credit_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_info', models.TextField(blank=True, null=True)),
                ('task_of_the_day', models.BooleanField(default=False)),
                ('conversion_window_days', models.IntegerField(blank=True, null=True)),
                ('available_to_level_1', models.BooleanField(default=False)),
                ('featured_offer', models.BooleanField(default=False)),
                ('custom_cta_label', models.CharField(blank=True, max_length=255, null=True)),
                ('smart_rank_score_filter', models.BooleanField(default=False)),
                ('smart_rank_score', models.FloatField(blank=True, null=True)),
                ('show_in_sections', models.BooleanField(default=False)),
                ('link_to_contest', models.BooleanField(default=False)),
                ('vendor_visibility', models.BooleanField(default=True)),
                ('platform_type', models.CharField(blank=True, max_length=50, null=True)),
                ('product_position_rank', models.IntegerField(blank=True, null=True)),
                ('sponsored_flag', models.BooleanField(default=False)),
                ('fraud_flag', models.BooleanField(default=False)),
                ('success_ratio_req', models.FloatField(blank=True, null=True)),
                ('geo_targeting', models.TextField(blank=True, null=True)),
                ('user_targeting_tags', models.TextField(blank=True, null=True)),
                ('click_behavior', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_wall', models.BooleanField(default=False)),
                ('trigger_badge_unlock', models.BooleanField(default=False)),
                ('review_module_for_app', models.BooleanField(default=False)),
                ('my_lead', models.BooleanField(default=False)),
                ('minimum_cart_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carousel_image_1', models.ImageField(blank=True, null=True, upload_to='digitalstore/carousel/')),
                ('carousel_image_2', models.ImageField(blank=True, null=True, upload_to='digitalstore/carousel/')),
                ('carousel_image_3', models.ImageField(blank=True, null=True, upload_to='digitalstore/carousel/')),
                ('carousel_image_4', models.ImageField(blank=True, null=True, upload_to='digitalstore/carousel/')),
                ('product_inr_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_quebes_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('enable_max_user', models.BooleanField(default=False)),
                ('max_purchase_per_user', models.IntegerField(blank=True, null=True)),
                ('inventory', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('android_id', models.CharField(blank=True, max_length=255, null=True)),
                ('imei_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('fraud_flag', models.BooleanField(default=False)),
                ('postback_url', models.URLField(blank=True, null=True)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalstore.digitalproduct')),
            ],
        ),
    ]
