# Generated by Django 5.2.5 on 2025-09-03 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalproduct',
            name='milestone_description',
        ),
        migrations.RemoveField(
            model_name='digitalproduct',
            name='milestone_name',
        ),
        migrations.RemoveField(
            model_name='digitalproduct',
            name='milestone_payout',
        ),
        migrations.RemoveField(
            model_name='digitalproduct',
            name='milestone_type',
        ),
        migrations.CreateModel(
            name='DigitalProductMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=255)),
                ('milestone_type', models.CharField(max_length=100)),
                ('milestone_description', models.TextField(blank=True, null=True)),
                ('milestone_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('digital_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='digitalstore.digitalproduct')),
            ],
        ),
    ]
